import type { LanguageGameContent } from './types';

export const enGameContent: LanguageGameContent = {
  languageCode: 'en',
  letterMatch: [
    {
      id: 'en-lm-1',
      prompt: 'Find the letter "b" as in "ball"!',
      targetLetter: 'b',
      audioPronunciation: 'b',
      options: ['d', 'b', 'p', 'q'],
      correctIndex: 1,
      hint: 'The letter "b" has its round belly pointing to the right!',
    },
    {
      id: 'en-lm-2',
      prompt: 'Find the letter "m" as in "monkey"!',
      targetLetter: 'm',
      audioPronunciation: 'm',
      options: ['w', 'n', 'm', 'u'],
      correctIndex: 2,
      hint: 'Letter "m" has two friendly arches on top!',
    },
    {
      id: 'en-lm-3',
      prompt: 'Find the letter "p" as in "panda"!',
      targetLetter: 'p',
      audioPronunciation: 'p',
      options: ['q', 'p', 'b', 'd'],
      correctIndex: 1,
      hint: 'Letter "p" has a circle resting near the top right!',
    },
    {
      id: 'en-lm-4',
      prompt: 'Find the letter "s" as in "sun"!',
      targetLetter: 's',
      audioPronunciation: 's',
      options: ['c', 'z', 's', 'x'],
      correctIndex: 2,
      hint: 'Letter "s" curves gracefully like a little snake!',
    },
  ],
  wordBuilder: [
    {
      id: 'en-wb-1',
      word: 'CAT',
      scrambledLetters: ['T', 'C', 'A'],
      meaningEmoji: '🐱',
      clue: 'A friendly furry pet that loves to purr.',
      audioPronunciation: 'cat',
    },
    {
      id: 'en-wb-2',
      word: 'STAR',
      scrambledLetters: ['A', 'S', 'T', 'R'],
      meaningEmoji: '⭐',
      clue: 'Twinkles brightly in the clear night sky.',
      audioPronunciation: 'star',
    },
    {
      id: 'en-wb-3',
      word: 'FROG',
      scrambledLetters: ['R', 'F', 'O', 'G'],
      meaningEmoji: '🐸',
      clue: 'A green hopper that leaps near peaceful ponds.',
      audioPronunciation: 'frog',
    },
    {
      id: 'en-wb-4',
      word: 'BIRD',
      scrambledLetters: ['D', 'B', 'R', 'I'],
      meaningEmoji: '🐦',
      clue: 'Spreads sweet wings and sings lovely morning tunes.',
      audioPronunciation: 'bird',
    },
  ],
  spellQuest: [
    {
      id: 'en-sq-1',
      word: 'SUN',
      audioPrompt: 'sun',
      meaningEmoji: '☀️',
      clue: 'The golden star that brings us daylight and warm sunshine.',
      letterBank: ['S', 'U', 'N', 'T', 'O', 'M'],
    },
    {
      id: 'en-sq-2',
      word: 'FISH',
      audioPrompt: 'fish',
      meaningEmoji: '🐟',
      clue: 'Swims gracefully underwater with shimmering fins.',
      letterBank: ['F', 'I', 'S', 'H', 'E', 'P'],
    },
    {
      id: 'en-sq-3',
      word: 'TREE',
      audioPrompt: 'tree',
      meaningEmoji: '🌳',
      clue: 'Tall living friend with branches and green rustling leaves.',
      letterBank: ['T', 'R', 'E', 'A', 'N', 'K'],
    },
    {
      id: 'en-sq-4',
      word: 'BOOK',
      audioPrompt: 'book',
      meaningEmoji: '📚',
      clue: 'Filled with pages, magic stories, and exciting journeys.',
      letterBank: ['B', 'O', 'O', 'K', 'L', 'D'],
    },
  ],
  readAloud: [
    {
      id: 'en-ra-1',
      sentence: 'The happy puppy plays with a colorful ball.',
      audioPronunciation: 'The happy puppy plays with a colorful ball.',
      phonemeTokens: [
        { word: 'The', phonetic: 'the' },
        { word: 'happy', phonetic: 'hap-py' },
        { word: 'puppy', phonetic: 'pup-py' },
        { word: 'plays', phonetic: 'plays' },
        { word: 'with', phonetic: 'with' },
        { word: 'a', phonetic: 'a' },
        { word: 'colorful', phonetic: 'col-or-ful' },
        { word: 'ball', phonetic: 'ball' },
      ],
      meaningEmoji: '🐶',
      encouragement: 'Terrific pace and clear pronunciation!',
    },
    {
      id: 'en-ra-2',
      sentence: 'A little blue bird sings atop the garden wall.',
      audioPronunciation: 'A little blue bird sings atop the garden wall.',
      phonemeTokens: [
        { word: 'A', phonetic: 'a' },
        { word: 'little', phonetic: 'lit-tle' },
        { word: 'blue', phonetic: 'blue' },
        { word: 'bird', phonetic: 'bird' },
        { word: 'sings', phonetic: 'sings' },
        { word: 'atop', phonetic: 'a-top' },
        { word: 'the', phonetic: 'the' },
        { word: 'garden', phonetic: 'gar-den' },
        { word: 'wall', phonetic: 'wall' },
      ],
      meaningEmoji: '🐦',
      encouragement: 'Wonderful cadence and expressive sound!',
    },
    {
      id: 'en-ra-3',
      sentence: 'Luna loves reading exciting adventures before bedtime.',
      audioPronunciation: 'Luna loves reading exciting adventures before bedtime.',
      phonemeTokens: [
        { word: 'Luna', phonetic: 'lu-na' },
        { word: 'loves', phonetic: 'loves' },
        { word: 'reading', phonetic: 'read-ing' },
        { word: 'exciting', phonetic: 'ex-cit-ing' },
        { word: 'adventures', phonetic: 'ad-ven-tures' },
        { word: 'before', phonetic: 'be-fore' },
        { word: 'bedtime', phonetic: 'bed-time' },
      ],
      meaningEmoji: '📖',
      encouragement: 'Outstanding reading flow and phonemic precision!',
    },
  ],
  soundBuilder: [
    {
      id: 'en-sb-1',
      soundPrompt: 'Which letter makes the bouncy /b/ sound as in "ball"?',
      audioSound: 'b',
      targetLetter: 'B',
      options: [
        { letter: 'B', sound: '/b/', exampleWord: 'Ball' },
        { letter: 'D', sound: '/d/', exampleWord: 'Door' },
        { letter: 'P', sound: '/p/', exampleWord: 'Pen' },
        { letter: 'T', sound: '/t/', exampleWord: 'Top' },
      ],
      correctIndex: 0,
      clue: 'Think of "b" vibrating softly when you say "b-b-ball"!',
    },
    {
      id: 'en-sb-2',
      soundPrompt: 'Which letter makes the soft /s/ hissing sound as in "sun"?',
      audioSound: 's',
      targetLetter: 'S',
      options: [
        { letter: 'C', sound: '/k/', exampleWord: 'Cat' },
        { letter: 'S', sound: '/s/', exampleWord: 'Sun' },
        { letter: 'Z', sound: '/z/', exampleWord: 'Zoo' },
        { letter: 'F', sound: '/f/', exampleWord: 'Fish' },
      ],
      correctIndex: 1,
      clue: 'Think of air gently flowing through your teeth like "s-s-sun"!',
    },
    {
      id: 'en-sb-3',
      soundPrompt: 'Which letter makes the humming /m/ sound as in "moon"?',
      audioSound: 'm',
      targetLetter: 'M',
      options: [
        { letter: 'N', sound: '/n/', exampleWord: 'Nest' },
        { letter: 'W', sound: '/w/', exampleWord: 'Water' },
        { letter: 'M', sound: '/m/', exampleWord: 'Moon' },
        { letter: 'L', sound: '/l/', exampleWord: 'Leaf' },
      ],
      correctIndex: 2,
      clue: 'Press your lips together gently to make the "m-m-moon" hum!',
    },
  ],
  storyExplorer: [
    {
      id: 'en-se-1',
      title: "Oliver the Dragon's Colorful Kite",
      emoji: '🪁',
      paragraphs: [
        'Oliver is a gentle little dragon who loves flying bright kites in the gentle breeze.',
        'One sunny morning, his favorite red kite drifted upward and rested softly on a fluffy cloud.',
        'With a cheerful leap and a flap of his emerald wings, Oliver zoomed up and brought his kite back safely.',
      ],
      audioPrompt: 'Oliver is a gentle little dragon who loves flying bright kites in the gentle breeze.',
      questions: [
        {
          question: "What color was Oliver's favorite kite?",
          options: ['Bright Red', 'Golden Yellow', 'Deep Purple', 'Sky Blue'],
          correctIndex: 0,
          explanation: "The story mentions Oliver's favorite bright red kite!",
        },
        {
          question: 'How did Oliver reach the fluffy cloud?',
          options: [
            'He climbed a tall wooden ladder',
            'He leaped and flapped his emerald wings',
            'He called a giant rainbow balloon',
            'He waited for the wind to drop it',
          ],
          correctIndex: 1,
          explanation: 'Oliver cheerfully leaped and flapped his wings to fly up!',
        },
      ],
    },
  ],
};
