import type { LanguageGameContent } from './types';

export const taGameContent: LanguageGameContent = {
  languageCode: 'ta',
  letterMatch: [
    {
      id: 'ta-lm-1',
      prompt: 'கீழே உள்ளவற்றில் "ப" என்ற எழுத்தைத் தேர்ந்தெடுக்கவும்:',
      targetLetter: 'ப',
      audioPronunciation: 'ப',
      options: ['ட', 'ப', 'ம', 'ய'],
      correctIndex: 1,
      hint: '"ப" எழுத்து நேர்க்கோடும் கீழ் வளைவும் உடையது!',
    },
    {
      id: 'ta-lm-2',
      prompt: 'மூன்று சுழி "ண" என்ற எழுத்தைக் கண்டுபிடிக்கவும்:',
      targetLetter: 'ண',
      audioPronunciation: 'ண',
      options: ['ன', 'ண', 'ந', 'ல'],
      correctIndex: 1,
      hint: 'இந்த எழுத்தில் மூன்று வட்டச் சுழிகள் உள்ளன!',
    },
    {
      id: 'ta-lm-3',
      prompt: 'தமிழுக்கே உரிய சிறப்பு "ழ" என்ற எழுத்தைத் தேர்ந்தெடுக்கவும்:',
      targetLetter: 'ழ',
      audioPronunciation: 'ழ',
      options: ['ள', 'ல', 'ழ', 'ர'],
      correctIndex: 2,
      hint: 'இது நாக்கை மேல் அண்ணத்தில் மடித்து உச்சரிக்கும் சிறப்பு ழகரம்!',
    },
    {
      id: 'ta-lm-4',
      prompt: 'கீழே உள்ளவற்றில் "க" என்ற எழுத்தைக் கண்டுபிடிக்கவும்:',
      targetLetter: 'க',
      audioPronunciation: 'க',
      options: ['ச', 'த', 'க', 'ப'],
      correctIndex: 2,
      hint: '"க" எழுத்து மேல் படுக்கைக் கோட்டுடன் தொடங்கும்!',
    },
  ],
  wordBuilder: [
    {
      id: 'ta-wb-1',
      word: 'படம்',
      scrambledLetters: ['ட', 'ப', 'ம்'],
      meaningEmoji: '🖼️',
      clue: 'சுவரில் மாட்டப்படும் அழகான ஓவியம் அல்லது சித்திரம்.',
      audioPronunciation: 'படம்',
    },
    {
      id: 'ta-wb-2',
      word: 'மரம்',
      scrambledLetters: ['ர', 'ம', 'ம்'],
      meaningEmoji: '🌳',
      clue: 'பச்சை இலைகளும் குளிர்ந்த நிழலும் தரும் இயற்கை நண்பன்.',
      audioPronunciation: 'மரம்',
    },
    {
      id: 'ta-wb-3',
      word: 'நிலா',
      scrambledLetters: ['லா', 'நி'],
      meaningEmoji: '🌙',
      clue: 'இரவு வானில் அழகாக ஒளி வீசும் வெண்மதி.',
      audioPronunciation: 'நிலா',
    },
    {
      id: 'ta-wb-4',
      word: 'பந்து',
      scrambledLetters: ['து', 'ப', 'ந்'],
      meaningEmoji: '⚽',
      clue: 'குழந்தைகள் ஓடி விளையாடும் உருண்டை வடிவ விளையாட்டுப் பொருள்.',
      audioPronunciation: 'பந்து',
    },
  ],
  spellQuest: [
    {
      id: 'ta-sq-1',
      word: 'பந்து',
      audioPrompt: 'பந்து',
      meaningEmoji: '⚽',
      clue: 'குழந்தைகள் எறிந்து விளையாடும் உருண்டை வடிவம்.',
      letterBank: ['ப', 'ந்', 'து', 'ம', 'ர', 'ம்'],
    },
    {
      id: 'ta-sq-2',
      word: 'மயில்',
      audioPrompt: 'மயில்',
      meaningEmoji: '🦚',
      clue: 'அழகிய தோகையைக் கொண்ட நமது தேசியப் பறவை.',
      letterBank: ['ம', 'யி', 'ல்', 'க', 'ண்', 'ண'],
    },
    {
      id: 'ta-sq-3',
      word: 'மீன்',
      audioPrompt: 'மீன்',
      meaningEmoji: '🐟',
      clue: 'தெளிந்த நீரில் துள்ளி நீந்தும் சிறிய உயிரினம்.',
      letterBank: ['மீ', 'ன்', 'ண', 'ப', 'ல்', 'வ'],
    },
    {
      id: 'ta-sq-4',
      word: 'புத்தகம்',
      audioPrompt: 'புத்தகம்',
      meaningEmoji: '📖',
      clue: 'சுவையான கதைகளும் நல்ல அறிவும் தரும் ஏடு.',
      letterBank: ['பு', 'த்', 'த', 'க', 'ம்', 'ர'],
    },
  ],
  readAloud: [
    {
      id: 'ta-ra-1',
      sentence: 'சிறிய பூனை வெயில் தோட்டத்தில் விளையாடுகிறது.',
      audioPronunciation: 'சிறிய பூனை வெயில் தோட்டத்தில் விளையாடுகிறது.',
      phonemeTokens: [
        { word: 'சிறிய', phonetic: 'சி-றி-ய' },
        { word: 'பூனை', phonetic: 'பூ-னை' },
        { word: 'வெயில்', phonetic: 'வெ-யில்' },
        { word: 'தோட்டத்தில்', phonetic: 'தோட்-டத்-தில்' },
        { word: 'விளையாடுகிறது', phonetic: 'வி-ளை-யா-டு-கி-ற-து' },
      ],
      meaningEmoji: '🐱',
      encouragement: 'மிக அருமையான உச்சரிப்பும் அழகிய வாசிப்பும்!',
    },
    {
      id: 'ta-ra-2',
      sentence: 'பச்சை மரம் குளிர்ந்த நிழலைத் தருகிறது.',
      audioPronunciation: 'பச்சை மரம் குளிர்ந்த நிழலைத் தருகிறது.',
      phonemeTokens: [
        { word: 'பச்சை', phonetic: 'பச்-சை' },
        { word: 'மரம்', phonetic: 'ம-ரம்' },
        { word: 'குளிர்ந்த', phonetic: 'கு-ளிர்ந்-த' },
        { word: 'நிழலைத்', phonetic: 'நி-ழ-லைத்' },
        { word: 'தருகிறது', phonetic: 'த-ரு-கி-ற-து' },
      ],
      meaningEmoji: '🌳',
      encouragement: 'சிறப்பான வாசிப்பு வேகம் மற்றும் தெளிவு!',
    },
    {
      id: 'ta-ra-3',
      sentence: 'அன்பான நிலா இரவு வானில் இனிமையாகப் பிரகாசிக்கிறது.',
      audioPronunciation: 'அன்பான நிலா இரவு வானில் இனிமையாகப் பிரகாசிக்கிறது.',
      phonemeTokens: [
        { word: 'அன்பான', phonetic: 'அன்-பா-ன' },
        { word: 'நிலா', phonetic: 'நி-லா' },
        { word: 'இரவு', phonetic: 'இ-ர-வு' },
        { word: 'வானில்', phonetic: 'வா-னில்' },
        { word: 'இனிமையாகப்', phonetic: 'இ-னி-மை-யா-கப்' },
        { word: 'பிரகாசிக்கிறது', phonetic: 'பி-ர-கா-சிக்-கி-ற-து' },
      ],
      meaningEmoji: '🌙',
      encouragement: 'அற்புதம்! சொற்களைத் தெளிவாகவும் திருத்தமாகவும் படித்தீர்கள்!',
    },
  ],
  soundBuilder: [
    {
      id: 'ta-sb-1',
      soundPrompt: 'கீழே உள்ளவற்றில் "ப" ஒலி தரும் எழுத்தைத் தேர்ந்தெடுக்கவும்:',
      audioSound: 'ப',
      targetLetter: 'ப',
      options: [
        { letter: 'ப', sound: '/pa/', exampleWord: 'பந்து (Ball)' },
        { letter: 'ட', sound: '/da/', exampleWord: 'டமாரம் (Drum)' },
        { letter: 'ம', sound: '/ma/', exampleWord: 'மரம் (Tree)' },
        { letter: 'ய', sound: '/ya/', exampleWord: 'யானை (Elephant)' },
      ],
      correctIndex: 0,
      clue: 'உதடுகளைச் சேர்த்து உச்சரிக்கும் "ப" ஒலி!',
    },
    {
      id: 'ta-sb-2',
      soundPrompt: 'சிறப்பு ழகர "ழ" என்ற ஒலியைத் தேர்ந்தெடுக்கவும்:',
      audioSound: 'ழ',
      targetLetter: 'ழ',
      options: [
        { letter: 'ள', sound: '/la/', exampleWord: 'கிளி (Parrot)' },
        { letter: 'ல', sound: '/la/', exampleWord: 'பல் (Tooth)' },
        { letter: 'ழ', sound: '/zha/', exampleWord: 'தமிழ் (Tamil)' },
        { letter: 'ர', sound: '/ra/', exampleWord: 'மரம் (Tree)' },
      ],
      correctIndex: 2,
      clue: '"தமிழ்" என்ற சொல்லில் வரும் அழகான ழகர ஒலி!',
    },
    {
      id: 'ta-sb-3',
      soundPrompt: 'மெல்லின "ம" என்ற ஒலியைத் தேர்ந்தெடுக்கவும்:',
      audioSound: 'ம',
      targetLetter: 'ம',
      options: [
        { letter: 'ந', sound: '/na/', exampleWord: 'நரி (Fox)' },
        { letter: 'வ', sound: '/va/', exampleWord: 'வண்டி (Cart)' },
        { letter: 'ம', sound: '/ma/', exampleWord: 'மழை (Rain)' },
        { letter: 'ல', sound: '/la/', exampleWord: 'லட்டு (Sweet)' },
      ],
      correctIndex: 2,
      clue: 'மூக்கின் வழியாக மென்மையாக ஒலிக்கும் "ம" ஒலி!',
    },
  ],
  storyExplorer: [
    {
      id: 'ta-se-1',
      title: 'அணிலும் இனிய மாம்பழமும்',
      emoji: '🐿️',
      paragraphs: [
        'ஒரு பெரிய மாமரத்தில் சுட்டி அணில் ஒன்று துள்ளி விளையாடி வாழ்ந்து வந்தது.',
        'ஒரு நாள், கிளையில் பழுத்திருந்த இனிப்பான மாம்பழத்தை எடுத்து சுவைத்து மகிழ்ந்தது.',
        'தன் அன்பு நண்பனான சிறிய பறவைக்கும் ஒரு துண்டு பழத்தைப் பகிர்ந்து கொடுத்து மகிழ்ந்தது.',
      ],
      audioPrompt: 'ஒரு பெரிய மாமரத்தில் சுட்டி அணில் ஒன்று துள்ளி விளையாடி வாழ்ந்து வந்தது.',
      questions: [
        {
          question: 'அணில் எந்த மரத்தில் வாழ்ந்து வந்தது?',
          options: ['பெரிய மாமரம்', 'தென்னை மரம்', 'வாழை மரம்', 'ஆலமரம்'],
          correctIndex: 0,
          explanation: 'கதையில் சுட்டி அணில் பெரிய மாமரத்தில் வாழ்ந்ததாகக் கூறப்பட்டுள்ளது!',
        },
        {
          question: 'அணில் யாருடன் பழத்தைப் பகிர்ந்து கொண்டது?',
          options: ['தன் நண்பனான பறவை', 'தோட்டத்துப் பூனை', 'ஆற்று மீன்', 'காட்டு முயல்'],
          correctIndex: 0,
          explanation: 'அணில் தன் இனிய பறவை நண்பனுடன் அன்புடன் பகிர்ந்து கொண்டது!',
        },
      ],
    },
  ],
};
